### ISSUE TITLE
First and Last Name Assigned to ConvertKit First Name Only Field

### ISSUE THREAD

**Issue by curtisb16** [ConvertKit/convertkit-membermouse#15]
I've noticed 1.0.2 of this code is consistently taking the Full name (First name, Last name) entered in by my new customers in MemberMouse as they are filling out the checkout page, and is entering both the First Name and their Last Name fields (combined) into the single First Name field of the customer's new account in ConvertKit.

Not the end of the world, but in my ConvertKit emails to customers, when I use personalized merge tags to open an email like:

```
{% if subscriber.first_name != blank %}
Hello {{ subscriber.first_name }},
{% else %}
Hello,
{% endif %}
```

... it's not as not as informal and slick as I'd like it to be since it's outputting, "Hello Jack Tripper," instead of "Hello Jack," 

And some of this is my just my OCD wishing it was accurate. ;-)

Curtis

P.S. ~ I've been using v1.0.2 of this code (plugin) since late Jan of this year on my live website. Thank you to anyone who's been working on this plugin! 1.0.2 was a huge update for me to be able to add cancel tags!!

**Comment by tnorthcutt** [comment]
@curtisb16 sorry you've waited so long on this! I'm picking up work on this now, and will hopefully have an update for you soon.
