### ISSUE TITLE
Cancelled Members Rejoining In MemberMouse Not Receiving "Apply tag on add" Tag

### ISSUE THREAD

**Issue by curtisb16** [ConvertKit/convertkit-membermouse#16]
The add tag on add and add tag on cancel feature seems to be working really well, overall in v1.0.2. Except, I just noticed a situation that it’s not covering:

1. Customer joins as member
2. This 1.0.2 plugin adds "add tag.” Let's call the tag "**Member - Level 1**" - Great!
3. Months later, customer cancels membership
4. This 1.0.2 plugin adds "cancel tag." Let's call the tag “**Cancel - Level 1**” - Great!
5. My ConvertKit automation "rule" sees customer's new "**Cancel - Level 1**" tag, and automatically removes customer's "**Member - Level 1**" tag. (Not mandatory but I added this to keep it clean)
6. Months later, customer rejoins my membership, using their same MemberMouse account, but joins as level 2 product.
7. Even though I also already had a _level 2 product_ setup in this plugin with an "add tag" and a corresponding "cancel tag," this plugin isn't adding the "add tag" to my customer's existing ConvertKit account in this step after they rejoin their existing MemberMouse account.

This just happened to me again, and I looked into the customer's ConvertKit account, and I see the "**Cancel: Level 1**" tag, but it should have also added (in a perfect situation) a "**Member: Level 2**" (add) tag to ConvertKit as well in this step. So, my ConvertKit continues to treat this customer as a cancelled member and won't send them Member emails with their renewed membership. 

I assume this is maybe because the plugin is detecting the customer already has a MemberMouse account, and therefore this plugin isn't told to engage and add an "add tag." 

Is it possible for this plugin to re-add the appropriate "add tag" for previous members with an existing MemberMouse and ConvertKit account? 

Thanks!
Curtis

P.S. ~ I've been using v1.0.2 of this code (plugin) since late Jan of this year on my live website. Thank you to anyone who's been working on this plugin! 1.0.2 was a huge update for me to be able to add cancel tags!!

**Comment by n7studios** [comment]
Tested in the above PR and working, so closing. Thanks!
