### ISSUE TITLE
Check if customers can be tagged by bundles.

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-membermouse#9]
Member Mouse has a "bundle" option and a customer has 1 membership, but multiple bundles. She wants to tag in CK based on the bundle that was purchased, not the membership.

Check if it is possible to hook into the bundle and add a mapping for Bundle :arrow_right: CK Tag

ref: https://secure.helpscout.net/conversation/389120643/92696/?folderId=956509

**Comment by n7studios** [comment]
Resolved in #28
